[project]
name = "hubert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">= 3.8, < 3.12"
dependencies = [
    "fairseq>=0.12.2",
    "transformers>=4.46.3",
]
